### Register
POST http://localhost:3000/api/auth/register
Content-Type: application/json

{
  "username": "albertoi", 
  "password": "123456",
  "email": "albert0i@hotmail.com"
}

###
POST http://localhost:3000/api/auth/register
Content-Type: application/json

{
  "username": "berto", 
  "password": "654321",
  "email": "albert0i@hotmail.com"
}


### Login
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
  "username": "albertoi", 
  "password": "123456"
}


### Change user password
POST http://localhost:3000/api/auth/chgpwd
Content-Type: application/json

{
  "username": "albertoi", 
  "password": "654321",
  "newPassword":"123456"
}

# 
# REST Client for Visual Studio Code
# https://marketplace.visualstudio.com/items?itemName=humao.rest-client
#