### Login
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
  "username": "albertoi", 
  "password": "123456"
}

# 
# REST Client for Visual Studio Code
# https://marketplace.visualstudio.com/items?itemName=humao.rest-client
#